- title: "Houseplants"
  details: "This variety of the popular succulent Aloe has curved, pointed leaves that are pale green with white spots and a spikey trim. This attractive and easy-to-care-for gem is the perfect addition to any bright space."
  button_text: "Add to Cart"
  image: "/images/photos/aloe-large.jpg"
  url: "/plants/"

- title: "Pots"
  details: "This variety of the popular succulent Aloe has curved, pointed leaves that are pale green with white spots and a spikey trim. This attractive and easy-to-care-for gem is the perfect addition to any bright space."
  button_text: "Add to Cart"
  image: "/images/photos/aloe-large.jpg"
  url: "/pots/"

- title: "Stands"
  details: "This variety of the popular succulent Aloe has curved, pointed leaves that are pale green with white spots and a spikey trim. This attractive and easy-to-care-for gem is the perfect addition to any bright space."
  button_text: "Add to Cart"
  image: "/images/photos/aloe-large.jpg"
  url: "/hangers/"
