title: "Buttons"
description: |
  Different button styles and their reasons.

patterns:
  basic:
    title: "Most Basic Button"
    description: |
      Basic button to be used for most button needs.
    fields:
      - name: text
        type: string
        example: "Learn More"

  ghost:
    description: |
      The Ghost buttons are to be used when an alternate button is needed.
    width: 400
