title: "Buttons"
description: |
  Different button styles and their reasons.

patterns:
  basic:
    title: "Most Basic Button"
    description: |
      Basic button to be used for most button needs.
    fields:
      - name: text
        type: string
        example: "Learn More"
      - name: url
        type: url
        example: "/plants/"

  ghost:
    description: |
      The Ghost buttons are to be used in the occasion a floating button is needed on a banner or large image.
    width: 400
