title: "Header"
description: |
  The header should be used for all pages, and consistsof the masthead containing the navigation as well as the logo. A simple decorative header to be used on all pages for consistency and clarity.
  be used on all pages for consistency and clarity.
