patterns:
  image:
    width: 400
    description: |
      The product card is used on the plants, pots, and hangers page in order to display specific products that can be added directly to the cart. Not to be used on the products page.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  product-card:
    width: 300
    description: |
      The product card is used on the plants, pots, and hangers page in order to display specific products that can be added directly to the cart. Not to be used on the products page.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
